import Navbar from "@/components/Navbar";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <main className="bg-black h-screen">
      <div className={`mx-auto max-w-[1240px] grid grid-cols-12 gap-4`}>
        <div className="grid col-span-3">
          <Navbar />
        </div>
        <div className="col-span-9 grid">{children}</div>
      </div>
    </main>
  );
}
