import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <main className="bg-black h-screen">
      <div className={`mx-auto max-w-[1240px]`}>{children}</div>
    </main>
  );
}
